namespace RolePlayingGame.Core
{
    public enum EntityType
    {
        Player,
        Boss1,
        Boss2,
        Boss3,
        Boss4,
        Boss5,
        Student1,
        Student2,
        Student3,
        Student4,
        Bones,

        //Health
        Burger,
        Chips,
        FryPotatoes,
        //Mana
        Water,
        Beer,
        Juice,
        //Knowledge
        IntroCSharp,
        DotNet,
        Msdn,
        //Defense
        Circuit,
        Keyboard,
        Monitor,
        //Doors
        UpDirectionOpen,
        SideOpen,
        //Obstacle
        StoneWall,
        BrickWall,
        WoodenWall,
        Tree,
        Bush,
        Table,
        TableLaptop,
        Chair,
        Column,
        River,
        //Paths
        Grass,
        Stairs,
        WoodenFloor,
        StoneFloor,
        Bridge
    }
}