namespace RolePlayingGame.Core
{
    public enum EntityType
    {
        Player,
        Boss,
        Student,

        //Health
        Burger,
        Chips,
        FryPotatoes,
        //Mana
        Water,
        Beer,
        Juice,
        //Knowledge
        IntroCSharp,
        DotNet,
        Msdn,
        //Defense
        Circuit,
        Keyboard,
        Monitor,
        //Doors
        UpDirectionOpen,
        SideOpen,
        //Obstacle
        StoneWall,
        BrickWall,
        WoodenWall,
        Tree,
        Bush,
        Table,
        TableLaptop,
        Chair,
        Column,
        River,
        //Paths
        Grass,
        Stairs,
        WoodenFloor,
        StoneFloor,
        Bridge
    }
}